# database
spring.datasource.url=jdbc:${DB_DIALECT}://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create
# files
spring.servlet.multipart.max-file-size=10MB
# bucket
bucket.access.host=${BUCKET_HOST}
bucket.access.port=${BUCKET_PORT}
bucket.access.key=${BUCKET_ACCESS_KEY}
bucket.access.secret=${BUCKET_ACCESS_SECRET}
bucket.access.name=${BUCKET_NAME}
# documentation
springdoc.api-docs.path=/api
springdoc.swagger-ui.path=/swagger.html
